name: Build, Validate, and Deploy Pelican Site to Hostinger

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  

jobs:
  build-validate-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install HTMLHint
        run:  npm install -g htmlhint

      - name: Build Pelican site
        run: pelican content -o output -s publishconf.py

      - name: Validate HTML
        run: npx htmlhint "output/**/*.html" || true

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUBL_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages










          
